# Generated by Django 2.2 on 2020-08-05 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete='DO_NOTHING', to=settings.AUTH_USER_MODEL),
        ),
    ]
